### PR TITLE
Client help pages

### PR DESCRIPTION
**Pull request by thomasf**
The basics is done now..

There are still not very suitable document pages for most of the "help" links in notifications.. Most are now pointed directly to the help index page for now.

### CODE REVIEW

**Comment by wsaqaf** [comment]
I think that makes sense. The help link points to the help English or Farsi
files depending on the language used?

Walid

**Comment by thomasf** [comment]
I'm creating another issue now with the most important other help pages we should add in the near future.

**Comment by thomasf** [comment]
help document links can point to either `/docs/__/document-name` which will use the current language, they can also point directly to `/docs/en/-document-name/` so it's quite flexible to decide where the docs points on a per link  basis..

There are only documents in english right now, we can either try to add one page per other language explaining the the docs are only available in english with a link to the english docs or take the user directly to the englush docs..

**Comment by thomasf** [comment]
Some screenshots with the formatting I added.. 

I removed the numbering from most of the documents and made them headings instead.

image

image

image

image

**Pull request merged**
